### ISSUE TITLE
ideal for mesh

### ISSUE THREAD

**Issue by bialystok** [DavidMurrayP2P/PhotonPowerZero#1]
Ideal solution for mesh network wifi. But guestion is how setup host?
How turn off-on network if power is to small. Meybe run host only few hours in day and few in night when the power is too small for working whole day.

**Comment by DavidMurrayP2P** [comment]
This is a use case that I am yet to try, but it is interesting. 

Yes so the board will currently gracefully shutdown the RPi when the LiPo battery voltage drops below 3.45V and switch it back on when the voltage has increased again past 3.75V. The size of the panel usually need to be massively over speced to have continuous 24x7 operation. Likely, as the battery depletes overnight the voltage will drop, the Pi will shutdown, and then resume the next morning after a couple of sunny hours.

**Comment by bialystok** [comment]
But communications we need to synchronize in some way? Let's say we send messages at twelve o'clock at night. And we want to get a reply, but we only have electricity during the day. 

If there are more nodes we need to arrange when we transmit so that several nodes have electricity at the same time so that we don't transmit when another node is sleeping. And if we make to talk always at the same time there will be no bandwidth.

The second issue is the replaceable battery. I would prefer it to be 18650, for example, in a 2 piece or three piece version. But charged separately. Discharged separately. And that I could in an emergency situation use any capacity of them. e.g. each different and one empty because I just took to the flashlight.
No remove lipo but using 18650 or(and) lipo (and) solar panel.

[ look at https://reticulum.network/ and meybe test communications with cc1101 or esp32Lora ]

**Comment by DavidMurrayP2P** [comment]
Thanks for the feedback. You can certainly use a larger battery and a larger solar panel. Perhaps the Pi Zero will get more efficient with time which will reduce the cost, in terms of solar size and battery size to build a 24x7 mesh node. This may be possible right now with the right conditions, but it is not yet something that I have tested, and testing in Australia may yield different results from winter in Norway.

**Comment by bialystok** [comment]
That's why he doesn't write about it always being 24/7. The idea is that the overlay should allow for different boot scenarios. Depending on the time but also on the capacity/amount of current power.

Electricity can always be in short supply. Even because there is a blockout. But we want to ensure that the network works when the amount of resources is not ideal
